env:
  ip: 192.168.0.100
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${env.ip}:8848
      config:
        server-addr: ${env.ip}:8848
        file-extension: yaml
        import-check:
          enabled: false
        prefix: PREFIX
        group: GROUP
        namespace: NAMESPACE

  application:
    name: service-template
  main:
    web-application-type: reactive
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

  #  datasource:
  #    driver-class-name: com.alibaba.druid.proxy.DruidDriver
  #    url: jdbc:mysql://${env.ip}:3306/yuoj
  #    username: root
  #    password: 123456

  #  redis:
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  #    database: 1
  #    password:

  rabbitmq:
    host: ${env.ip}
    port: 5672
    password: guest
    username: guest




server:
  #  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/judge
    session:
      cookie:
        max-age: 2592000 # cookie 30 天过期
        path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）