env:
  ip: 127.0.0.1
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${env.ip}:8848
      config:
        server-addr: ${env.ip}:8848
        import-check:
          enabled: false
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: service-template # 路由规则id，自定义，唯一
          uri: lb://service-template # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言（匹配条件），判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/template/** # 这里是以请求路径作为判断规则
          filters:
            - StripPrefix=1
  application:
    name: gateway
  main:
    web-application-type: reactive
server:
  port: 8101